# Generated by Django 6.0.6 on 2026-07-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplefin_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_date', models.DateTimeField()),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFinConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_url', models.TextField()),
            ],
            options={
                'verbose_name': 'SimpleFIN Connection',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simplefin_id', models.CharField(max_length=255, unique=True)),
                ('posted', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('payee', models.CharField(blank=True, default='', max_length=255)),
                ('memo', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('pending', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='simplefin_app.account')),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
    ]
